# AI x Blockchain KOL Voice Evolution Configuration
# Defines target voice parameters and progression milestones

# Voice Evolution Framework
voice_evolution:
  # Current Baseline (December 17, 2025)
  baseline:
    technical_expertise: 0.00    # Biggest opportunity
    conversational: 0.17         # Natural differentiator - maintain
    enthusiasm: 0.13             # Primary engagement driver (0.49 correlation)
    authority: 0.00              # Build through technical content
    helpfulness: 0.03            # Increase educational value
    approachability: 0.05        # Natural strength
    
  # Phase 1 Targets (Month 1-2): Foundation Building  
  phase_1_targets:
    technical_expertise: 0.25    # Basic AI x blockchain commentary
    authority: 0.20              # Confident takes on convergence topics
    enthusiasm: 0.25             # Increase from baseline to optimize engagement
    conversational: 0.17         # Maintain as differentiator
    helpfulness: 0.15            # Increase educational value
    approachability: 0.05        # Maintain natural strength
    
  # Phase 2 Targets (Month 3-4): Authority Development
  phase_2_targets:
    technical_expertise: 0.50    # Deep dive technical threads
    authority: 0.45              # Strong technical positions
    innovation_focus: 0.65       # Trend prediction content
    enthusiasm: 0.30             # Maintain engagement driver
    conversational: 0.15         # Slight decrease as authority increases
    helpfulness: 0.25            # Educational but authoritative
    
  # Phase 3 Targets (Month 5-6): Thought Leadership
  phase_3_targets:
    technical_expertise: 0.75    # High-level AI x blockchain insights
    authority: 0.70              # Confident takes on convergence topics
    innovation_focus: 0.80       # Cutting-edge development commentary
    forward_thinking: 0.85       # Ahead-of-trends predictions
    enthusiasm: 0.30             # Maintain engagement effectiveness
    conversational: 0.40         # Professional but accessible
    helpfulness: 0.65            # Educational but authoritative

# Content Generation Parameters
content_generation:
  # AI x Blockchain Focus Areas (Distribution)
  content_pillars:
    ai_agents_unichain: 0.30     # 30% - Autonomous trading, intelligent hooks
    hft_ai_integration: 0.25     # 25% - ML models, trading strategies
    technical_innovation: 0.25   # 25% - Breaking developments, analysis
    strategic_engagement: 0.20   # 20% - Community building, relationships
    
  # Technical Depth by Content Type
  technical_depth_targets:
    threads: 0.80                # High technical depth for threads
    replies: 0.60                # Moderate technical depth for replies
    quotes: 0.70                 # Good technical depth for quote tweets
    original: 0.75               # Strong technical depth for original content
    
  # Voice Tone Evolution
  tone_progression:
    month_1: "helpful_technical"           # Helpful with technical elements
    month_2: "confident_educational"       # More confident, still educational
    month_3: "authoritative_approachable"  # Authority building, maintain accessibility
    month_4: "thought_leader_engaging"     # Clear thought leadership, engaging
    month_5: "innovation_expert"           # Innovation and trend expert
    month_6: "ai_blockchain_authority"     # Recognized convergence authority

# Engagement Strategy Evolution
engagement_strategy:
  # Current Strategy
  baseline_approach:
    response_style: "enthusiastic_helpful"
    technical_level: "basic_explanations"
    authority_positioning: "learner_sharer"
    
  # Phase 1 Evolution (Week 1-8)
  phase_1_approach:
    response_style: "confident_helpful"
    technical_level: "intermediate_insights"
    authority_positioning: "knowledgeable_contributor"
    content_focus: "ai_blockchain_basics"
    
  # Phase 2 Evolution (Week 9-16)
  phase_2_approach:
    response_style: "authoritative_accessible"
    technical_level: "advanced_analysis"
    authority_positioning: "technical_expert"
    content_focus: "convergence_deep_dives"
    
  # Phase 3 Evolution (Week 17-24)
  phase_3_approach:
    response_style: "thought_leader_engaging"
    technical_level: "cutting_edge_insights"
    authority_positioning: "industry_thought_leader"
    content_focus: "innovation_predictions"

# Content Templates by Evolution Phase
content_templates:
  # Phase 1: Foundation Building
  phase_1_templates:
    - "Interesting development in [AI x blockchain topic]. The [technical aspect] shows potential for [practical application]"
    - "Building on this [blockchain concept] with AI integration could [specific improvement]. Thoughts on implementation approaches?"
    - "The convergence of [AI technology] and [blockchain protocol] is fascinating. Here's why [technical reasoning]"
    
  # Phase 2: Authority Development  
  phase_2_templates:
    - "Hot take: [AI x blockchain prediction] because [technical analysis]. The infrastructure pieces are [status assessment] 🧵"
    - "Deep dive on [convergence topic]: [technical framework]. This changes [industry aspect] in [specific ways]"
    - "Why [AI blockchain integration] matters: [technical reasoning] + [market implications] = [forward-looking conclusion]"
    
  # Phase 3: Thought Leadership
  phase_3_templates:
    - "[AI x blockchain trend] isn't just about [surface benefit] - it's fundamentally reshaping [infrastructure/protocols/trading]"
    - "Prediction: [forward-looking analysis] will drive the next wave of [AI blockchain convergence]. Here's the technical roadmap 🧵"
    - "The [technical innovation] everyone's missing: [unique insight] creates [unprecedented opportunity] for [specific application]"

# Success Metrics by Phase
success_metrics:
  # Voice Consistency Tracking
  voice_alignment_targets:
    month_1: 0.70                # Good alignment with evolved voice
    month_3: 0.80                # Strong alignment 
    month_6: 0.90                # Excellent alignment
    
  # Engagement Correlation Targets
  engagement_improvements:
    baseline_correlation: 0.49   # Current enthusiasm correlation
    month_1_target: 0.55         # Improved engagement
    month_3_target: 0.65         # Strong improvement
    month_6_target: 0.75         # Excellent engagement correlation
    
  # Technical Authority Indicators
  authority_metrics:
    technical_discussion_ratio:
      month_1: 0.30              # 30% technical discussions
      month_3: 0.50              # 50% technical discussions  
      month_6: 0.70              # 70% technical discussions
    strategic_account_engagement:
      month_1: 0.20              # 20% engagements with strategic accounts
      month_3: 0.35              # 35% strategic engagement
      month_6: 0.50              # 50% strategic engagement

# A/B Testing Framework
ab_testing:
  # Voice Parameter Testing
  test_parameters:
    - technical_expertise: [0.20, 0.30]  # Test different technical levels
    - authority: [0.15, 0.25]            # Test authority positioning
    - enthusiasm: [0.20, 0.30]           # Test engagement optimization
    
  # Content Type Testing
  content_experiments:
    - thread_vs_reply_technical_depth
    - quote_vs_original_authority_positioning
    - hashtag_ai_blockchain_vs_traditional
    
  # Timing Testing
  timing_experiments:
    - immediate_vs_delayed_strategic_responses
    - work_hours_vs_evening_technical_content
    - weekend_vs_weekday_innovation_posts

# Monitoring and Adjustment
monitoring:
  # Weekly Voice Analysis
  weekly_tracking:
    - voice_characteristic_progression
    - engagement_correlation_changes
    - content_performance_by_voice_parameters
    - strategic_account_response_rates
    
  # Monthly Strategic Reviews
  monthly_assessment:
    - progress_toward_target_voice_profile
    - competitive_positioning_analysis
    - community_recognition_indicators
    - adjustment_recommendations
    
  # Quarterly Optimization
  quarterly_optimization:
    - voice_evolution_strategy_refinement
    - content_pillar_distribution_adjustment
    - strategic_account_targeting_updates
    - authority_building_acceleration_opportunities